// FICHIER GENERE par tools/build-perso.js — ne pas modifier a la main.
// SPRITES[perso][etape 0..19][direction 0..7] : image 512 x 512 du perso
// (null : etape pas encore dessinee dans ce style, voir humain-realiste).
// Directions : 0 = face, puis on tourne (sud-est, est, nord-est, dos, ...).

export const SPRITES = {
  "humain": [
    [require("./assets/perso/humain/rot/1/0.png"), require("./assets/perso/humain/rot/1/1.png"), require("./assets/perso/humain/rot/1/2.png"), require("./assets/perso/humain/rot/1/3.png"), require("./assets/perso/humain/rot/1/4.png"), require("./assets/perso/humain/rot/1/5.png"), require("./assets/perso/humain/rot/1/6.png"), require("./assets/perso/humain/rot/1/7.png")],
    [require("./assets/perso/humain/rot/2/0.png"), require("./assets/perso/humain/rot/2/1.png"), require("./assets/perso/humain/rot/2/2.png"), require("./assets/perso/humain/rot/2/3.png"), require("./assets/perso/humain/rot/2/4.png"), require("./assets/perso/humain/rot/2/5.png"), require("./assets/perso/humain/rot/2/6.png"), require("./assets/perso/humain/rot/2/7.png")],
    [require("./assets/perso/humain/rot/3/0.png"), require("./assets/perso/humain/rot/3/1.png"), require("./assets/perso/humain/rot/3/2.png"), require("./assets/perso/humain/rot/3/3.png"), require("./assets/perso/humain/rot/3/4.png"), require("./assets/perso/humain/rot/3/5.png"), require("./assets/perso/humain/rot/3/6.png"), require("./assets/perso/humain/rot/3/7.png")],
    [require("./assets/perso/humain/rot/4/0.png"), require("./assets/perso/humain/rot/4/1.png"), require("./assets/perso/humain/rot/4/2.png"), require("./assets/perso/humain/rot/4/3.png"), require("./assets/perso/humain/rot/4/4.png"), require("./assets/perso/humain/rot/4/5.png"), require("./assets/perso/humain/rot/4/6.png"), require("./assets/perso/humain/rot/4/7.png")],
    [require("./assets/perso/humain/rot/5/0.png"), require("./assets/perso/humain/rot/5/1.png"), require("./assets/perso/humain/rot/5/2.png"), require("./assets/perso/humain/rot/5/3.png"), require("./assets/perso/humain/rot/5/4.png"), require("./assets/perso/humain/rot/5/5.png"), require("./assets/perso/humain/rot/5/6.png"), require("./assets/perso/humain/rot/5/7.png")],
    [require("./assets/perso/humain/rot/6/0.png"), require("./assets/perso/humain/rot/6/1.png"), require("./assets/perso/humain/rot/6/2.png"), require("./assets/perso/humain/rot/6/3.png"), require("./assets/perso/humain/rot/6/4.png"), require("./assets/perso/humain/rot/6/5.png"), require("./assets/perso/humain/rot/6/6.png"), require("./assets/perso/humain/rot/6/7.png")],
    [require("./assets/perso/humain/rot/7/0.png"), require("./assets/perso/humain/rot/7/1.png"), require("./assets/perso/humain/rot/7/2.png"), require("./assets/perso/humain/rot/7/3.png"), require("./assets/perso/humain/rot/7/4.png"), require("./assets/perso/humain/rot/7/5.png"), require("./assets/perso/humain/rot/7/6.png"), require("./assets/perso/humain/rot/7/7.png")],
    [require("./assets/perso/humain/rot/8/0.png"), require("./assets/perso/humain/rot/8/1.png"), require("./assets/perso/humain/rot/8/2.png"), require("./assets/perso/humain/rot/8/3.png"), require("./assets/perso/humain/rot/8/4.png"), require("./assets/perso/humain/rot/8/5.png"), require("./assets/perso/humain/rot/8/6.png"), require("./assets/perso/humain/rot/8/7.png")],
    [require("./assets/perso/humain/rot/9/0.png"), require("./assets/perso/humain/rot/9/1.png"), require("./assets/perso/humain/rot/9/2.png"), require("./assets/perso/humain/rot/9/3.png"), require("./assets/perso/humain/rot/9/4.png"), require("./assets/perso/humain/rot/9/5.png"), require("./assets/perso/humain/rot/9/6.png"), require("./assets/perso/humain/rot/9/7.png")],
    [require("./assets/perso/humain/rot/10/0.png"), require("./assets/perso/humain/rot/10/1.png"), require("./assets/perso/humain/rot/10/2.png"), require("./assets/perso/humain/rot/10/3.png"), require("./assets/perso/humain/rot/10/4.png"), require("./assets/perso/humain/rot/10/5.png"), require("./assets/perso/humain/rot/10/6.png"), require("./assets/perso/humain/rot/10/7.png")],
    [require("./assets/perso/humain/rot/11/0.png"), require("./assets/perso/humain/rot/11/1.png"), require("./assets/perso/humain/rot/11/2.png"), require("./assets/perso/humain/rot/11/3.png"), require("./assets/perso/humain/rot/11/4.png"), require("./assets/perso/humain/rot/11/5.png"), require("./assets/perso/humain/rot/11/6.png"), require("./assets/perso/humain/rot/11/7.png")],
    [require("./assets/perso/humain/rot/12/0.png"), require("./assets/perso/humain/rot/12/1.png"), require("./assets/perso/humain/rot/12/2.png"), require("./assets/perso/humain/rot/12/3.png"), require("./assets/perso/humain/rot/12/4.png"), require("./assets/perso/humain/rot/12/5.png"), require("./assets/perso/humain/rot/12/6.png"), require("./assets/perso/humain/rot/12/7.png")],
    [require("./assets/perso/humain/rot/13/0.png"), require("./assets/perso/humain/rot/13/1.png"), require("./assets/perso/humain/rot/13/2.png"), require("./assets/perso/humain/rot/13/3.png"), require("./assets/perso/humain/rot/13/4.png"), require("./assets/perso/humain/rot/13/5.png"), require("./assets/perso/humain/rot/13/6.png"), require("./assets/perso/humain/rot/13/7.png")],
    [require("./assets/perso/humain/rot/14/0.png"), require("./assets/perso/humain/rot/14/1.png"), require("./assets/perso/humain/rot/14/2.png"), require("./assets/perso/humain/rot/14/3.png"), require("./assets/perso/humain/rot/14/4.png"), require("./assets/perso/humain/rot/14/5.png"), require("./assets/perso/humain/rot/14/6.png"), require("./assets/perso/humain/rot/14/7.png")],
    [require("./assets/perso/humain/rot/15/0.png"), require("./assets/perso/humain/rot/15/1.png"), require("./assets/perso/humain/rot/15/2.png"), require("./assets/perso/humain/rot/15/3.png"), require("./assets/perso/humain/rot/15/4.png"), require("./assets/perso/humain/rot/15/5.png"), require("./assets/perso/humain/rot/15/6.png"), require("./assets/perso/humain/rot/15/7.png")],
    [require("./assets/perso/humain/rot/16/0.png"), require("./assets/perso/humain/rot/16/1.png"), require("./assets/perso/humain/rot/16/2.png"), require("./assets/perso/humain/rot/16/3.png"), require("./assets/perso/humain/rot/16/4.png"), require("./assets/perso/humain/rot/16/5.png"), require("./assets/perso/humain/rot/16/6.png"), require("./assets/perso/humain/rot/16/7.png")],
    [require("./assets/perso/humain/rot/17/0.png"), require("./assets/perso/humain/rot/17/1.png"), require("./assets/perso/humain/rot/17/2.png"), require("./assets/perso/humain/rot/17/3.png"), require("./assets/perso/humain/rot/17/4.png"), require("./assets/perso/humain/rot/17/5.png"), require("./assets/perso/humain/rot/17/6.png"), require("./assets/perso/humain/rot/17/7.png")],
    [require("./assets/perso/humain/rot/18/0.png"), require("./assets/perso/humain/rot/18/1.png"), require("./assets/perso/humain/rot/18/2.png"), require("./assets/perso/humain/rot/18/3.png"), require("./assets/perso/humain/rot/18/4.png"), require("./assets/perso/humain/rot/18/5.png"), require("./assets/perso/humain/rot/18/6.png"), require("./assets/perso/humain/rot/18/7.png")],
    [require("./assets/perso/humain/rot/19/0.png"), require("./assets/perso/humain/rot/19/1.png"), require("./assets/perso/humain/rot/19/2.png"), require("./assets/perso/humain/rot/19/3.png"), require("./assets/perso/humain/rot/19/4.png"), require("./assets/perso/humain/rot/19/5.png"), require("./assets/perso/humain/rot/19/6.png"), require("./assets/perso/humain/rot/19/7.png")],
    [require("./assets/perso/humain/rot/20/0.png"), require("./assets/perso/humain/rot/20/1.png"), require("./assets/perso/humain/rot/20/2.png"), require("./assets/perso/humain/rot/20/3.png"), require("./assets/perso/humain/rot/20/4.png"), require("./assets/perso/humain/rot/20/5.png"), require("./assets/perso/humain/rot/20/6.png"), require("./assets/perso/humain/rot/20/7.png")],
  ],
  "chat": [
    [require("./assets/perso/chat/rot/1/0.png"), require("./assets/perso/chat/rot/1/1.png"), require("./assets/perso/chat/rot/1/2.png"), require("./assets/perso/chat/rot/1/3.png"), require("./assets/perso/chat/rot/1/4.png"), require("./assets/perso/chat/rot/1/5.png"), require("./assets/perso/chat/rot/1/6.png"), require("./assets/perso/chat/rot/1/7.png")],
    [require("./assets/perso/chat/rot/2/0.png"), require("./assets/perso/chat/rot/2/1.png"), require("./assets/perso/chat/rot/2/2.png"), require("./assets/perso/chat/rot/2/3.png"), require("./assets/perso/chat/rot/2/4.png"), require("./assets/perso/chat/rot/2/5.png"), require("./assets/perso/chat/rot/2/6.png"), require("./assets/perso/chat/rot/2/7.png")],
    [require("./assets/perso/chat/rot/3/0.png"), require("./assets/perso/chat/rot/3/1.png"), require("./assets/perso/chat/rot/3/2.png"), require("./assets/perso/chat/rot/3/3.png"), require("./assets/perso/chat/rot/3/4.png"), require("./assets/perso/chat/rot/3/5.png"), require("./assets/perso/chat/rot/3/6.png"), require("./assets/perso/chat/rot/3/7.png")],
    [require("./assets/perso/chat/rot/4/0.png"), require("./assets/perso/chat/rot/4/1.png"), require("./assets/perso/chat/rot/4/2.png"), require("./assets/perso/chat/rot/4/3.png"), require("./assets/perso/chat/rot/4/4.png"), require("./assets/perso/chat/rot/4/5.png"), require("./assets/perso/chat/rot/4/6.png"), require("./assets/perso/chat/rot/4/7.png")],
    [require("./assets/perso/chat/rot/5/0.png"), require("./assets/perso/chat/rot/5/1.png"), require("./assets/perso/chat/rot/5/2.png"), require("./assets/perso/chat/rot/5/3.png"), require("./assets/perso/chat/rot/5/4.png"), require("./assets/perso/chat/rot/5/5.png"), require("./assets/perso/chat/rot/5/6.png"), require("./assets/perso/chat/rot/5/7.png")],
    [require("./assets/perso/chat/rot/6/0.png"), require("./assets/perso/chat/rot/6/1.png"), require("./assets/perso/chat/rot/6/2.png"), require("./assets/perso/chat/rot/6/3.png"), require("./assets/perso/chat/rot/6/4.png"), require("./assets/perso/chat/rot/6/5.png"), require("./assets/perso/chat/rot/6/6.png"), require("./assets/perso/chat/rot/6/7.png")],
    [require("./assets/perso/chat/rot/7/0.png"), require("./assets/perso/chat/rot/7/1.png"), require("./assets/perso/chat/rot/7/2.png"), require("./assets/perso/chat/rot/7/3.png"), require("./assets/perso/chat/rot/7/4.png"), require("./assets/perso/chat/rot/7/5.png"), require("./assets/perso/chat/rot/7/6.png"), require("./assets/perso/chat/rot/7/7.png")],
    [require("./assets/perso/chat/rot/8/0.png"), require("./assets/perso/chat/rot/8/1.png"), require("./assets/perso/chat/rot/8/2.png"), require("./assets/perso/chat/rot/8/3.png"), require("./assets/perso/chat/rot/8/4.png"), require("./assets/perso/chat/rot/8/5.png"), require("./assets/perso/chat/rot/8/6.png"), require("./assets/perso/chat/rot/8/7.png")],
    [require("./assets/perso/chat/rot/9/0.png"), require("./assets/perso/chat/rot/9/1.png"), require("./assets/perso/chat/rot/9/2.png"), require("./assets/perso/chat/rot/9/3.png"), require("./assets/perso/chat/rot/9/4.png"), require("./assets/perso/chat/rot/9/5.png"), require("./assets/perso/chat/rot/9/6.png"), require("./assets/perso/chat/rot/9/7.png")],
    [require("./assets/perso/chat/rot/10/0.png"), require("./assets/perso/chat/rot/10/1.png"), require("./assets/perso/chat/rot/10/2.png"), require("./assets/perso/chat/rot/10/3.png"), require("./assets/perso/chat/rot/10/4.png"), require("./assets/perso/chat/rot/10/5.png"), require("./assets/perso/chat/rot/10/6.png"), require("./assets/perso/chat/rot/10/7.png")],
    [require("./assets/perso/chat/rot/11/0.png"), require("./assets/perso/chat/rot/11/1.png"), require("./assets/perso/chat/rot/11/2.png"), require("./assets/perso/chat/rot/11/3.png"), require("./assets/perso/chat/rot/11/4.png"), require("./assets/perso/chat/rot/11/5.png"), require("./assets/perso/chat/rot/11/6.png"), require("./assets/perso/chat/rot/11/7.png")],
    [require("./assets/perso/chat/rot/12/0.png"), require("./assets/perso/chat/rot/12/1.png"), require("./assets/perso/chat/rot/12/2.png"), require("./assets/perso/chat/rot/12/3.png"), require("./assets/perso/chat/rot/12/4.png"), require("./assets/perso/chat/rot/12/5.png"), require("./assets/perso/chat/rot/12/6.png"), require("./assets/perso/chat/rot/12/7.png")],
    [require("./assets/perso/chat/rot/13/0.png"), require("./assets/perso/chat/rot/13/1.png"), require("./assets/perso/chat/rot/13/2.png"), require("./assets/perso/chat/rot/13/3.png"), require("./assets/perso/chat/rot/13/4.png"), require("./assets/perso/chat/rot/13/5.png"), require("./assets/perso/chat/rot/13/6.png"), require("./assets/perso/chat/rot/13/7.png")],
    [require("./assets/perso/chat/rot/14/0.png"), require("./assets/perso/chat/rot/14/1.png"), require("./assets/perso/chat/rot/14/2.png"), require("./assets/perso/chat/rot/14/3.png"), require("./assets/perso/chat/rot/14/4.png"), require("./assets/perso/chat/rot/14/5.png"), require("./assets/perso/chat/rot/14/6.png"), require("./assets/perso/chat/rot/14/7.png")],
    [require("./assets/perso/chat/rot/15/0.png"), require("./assets/perso/chat/rot/15/1.png"), require("./assets/perso/chat/rot/15/2.png"), require("./assets/perso/chat/rot/15/3.png"), require("./assets/perso/chat/rot/15/4.png"), require("./assets/perso/chat/rot/15/5.png"), require("./assets/perso/chat/rot/15/6.png"), require("./assets/perso/chat/rot/15/7.png")],
    [require("./assets/perso/chat/rot/16/0.png"), require("./assets/perso/chat/rot/16/1.png"), require("./assets/perso/chat/rot/16/2.png"), require("./assets/perso/chat/rot/16/3.png"), require("./assets/perso/chat/rot/16/4.png"), require("./assets/perso/chat/rot/16/5.png"), require("./assets/perso/chat/rot/16/6.png"), require("./assets/perso/chat/rot/16/7.png")],
    [require("./assets/perso/chat/rot/17/0.png"), require("./assets/perso/chat/rot/17/1.png"), require("./assets/perso/chat/rot/17/2.png"), require("./assets/perso/chat/rot/17/3.png"), require("./assets/perso/chat/rot/17/4.png"), require("./assets/perso/chat/rot/17/5.png"), require("./assets/perso/chat/rot/17/6.png"), require("./assets/perso/chat/rot/17/7.png")],
    [require("./assets/perso/chat/rot/18/0.png"), require("./assets/perso/chat/rot/18/1.png"), require("./assets/perso/chat/rot/18/2.png"), require("./assets/perso/chat/rot/18/3.png"), require("./assets/perso/chat/rot/18/4.png"), require("./assets/perso/chat/rot/18/5.png"), require("./assets/perso/chat/rot/18/6.png"), require("./assets/perso/chat/rot/18/7.png")],
    [require("./assets/perso/chat/rot/19/0.png"), require("./assets/perso/chat/rot/19/1.png"), require("./assets/perso/chat/rot/19/2.png"), require("./assets/perso/chat/rot/19/3.png"), require("./assets/perso/chat/rot/19/4.png"), require("./assets/perso/chat/rot/19/5.png"), require("./assets/perso/chat/rot/19/6.png"), require("./assets/perso/chat/rot/19/7.png")],
    [require("./assets/perso/chat/rot/20/0.png"), require("./assets/perso/chat/rot/20/1.png"), require("./assets/perso/chat/rot/20/2.png"), require("./assets/perso/chat/rot/20/3.png"), require("./assets/perso/chat/rot/20/4.png"), require("./assets/perso/chat/rot/20/5.png"), require("./assets/perso/chat/rot/20/6.png"), require("./assets/perso/chat/rot/20/7.png")],
  ],
  "humain-realiste": [
    [require("./assets/perso/humain-realiste/rot/1/0.png"), require("./assets/perso/humain-realiste/rot/1/1.png"), require("./assets/perso/humain-realiste/rot/1/2.png"), require("./assets/perso/humain-realiste/rot/1/3.png"), require("./assets/perso/humain-realiste/rot/1/4.png"), require("./assets/perso/humain-realiste/rot/1/5.png"), require("./assets/perso/humain-realiste/rot/1/6.png"), require("./assets/perso/humain-realiste/rot/1/7.png")],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
};

// ANIMS[perso][etape 0..19][nom] : planche de l'animation vue de face
// (frames 512 x 512 en grille de `colonnes`), `n` frames de `ms` ms.
export const ANIMS = {
  "humain": [
    { idle: { planche: require("./assets/perso/humain/anim/idle/1.png"), n: 13, colonnes: 4, ms: 120 } },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
  ],
  "chat": [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
  ],
  "humain-realiste": [
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
    {  },
  ],
};
